export type ArtStyleOption = string | { label: string; options: string[] };
export type ArtStyles = Record<string, ArtStyleOption[]>;

export const artStyles: ArtStyles = {
  traditional: [
    {
      label: 'Classical and Renaissance',
      options: ['Renaissance', 'Mannerism', 'Baroque', 'Rococo'],
    },
    {
      label: '19th Century Art Movements',
      options: [
        'Neoclassicism',
        'Romanticism',
        'Realism',
        'Impressionism',
        'Post-Impressionism',
        'Symbolism',
        'Tonalism',
        'Art Nouveau',
      ],
    },
  ],
  contemporary: [
    'Anime',
    'Cartoon',
    'Digital Pixel Art',
    'Steampunk',
    'Cyberpunk',
    'Fantasy',
    'Sci-Fi',
    'Retro',
    'Vaporwave',
    'Graffiti',
    'Pin-Up',
    'Tattoo',
    'Chibi',
    'Comic Book',
    'Manga',
    'Retro Futurism',
    'Kawaii',
    'Doodle',
    'Whimsical',
    'Pop Surrealism',
    'Memphis',
  ],
  popArt: ['Pop Art', 'Pop Surrealism'],
  specialized: [
    'Fantasy',
    'Sci-Fi',
    'Steampunk',
    'Cyberpunk',
    'Retro',
    'Vaporwave',
    'Graffiti',
    'Pin-Up',
    'Tattoo',
    'Chibi',
    'Comic Book',
    'Manga',
    'Retro Futurism',
    'Kawaii',
    'Doodle',
    'Whimsical',
    'Pop Surrealism',
    'Memphis',
  ],
};
